name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    name: "create release"
    runs-on: "ubuntu-latest"

    steps:
      - name: get version
        run: VERSION=${{ github.ref_name }} && echo "PROJ_VERSION=${VERSION:1}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: build-osx64
        uses: ./.github/actions/build-dotnet
        with:
          name: 'ConsoleClient'
          runtime: osx-x64
          version: ${{ env.PROJ_VERSION }}
          build-args: --self-contained
          dotnet-version: '7.0'
      - name: build win-x86
        uses: ./.github/actions/build-dotnet
        with:
          name: 'ConsoleClient'
          runtime: win-x86
          version: ${{ env.PROJ_VERSION }}
          build-args: --self-contained
          dotnet-version: '7.0'
      - name: build linux-x64
        uses: ./.github/actions/build-dotnet
        with:
          name: 'ConsoleClient'
          runtime: linux-x64
          version: ${{ env.PROJ_VERSION }}
          build-args: --self-contained
          dotnet-version: '7.0'
      # Create the release
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/*.zip
