name: "test for action"
on:
  push:
    branches: [ "test" ]
  
jobs:
  test:
    name: test-action
    runs-on: ubuntu-latest
    
    steps:
      - name: get version
        run: echo "PROJ_VERSION=2.0.0" >> $GITHUB_ENV
      - id: build-osx64
        uses: devskar/build-dotnet@v1.1
        with:
          name: 'ConsoleClient'
          runtime: osx-x64
          version: ${{ env.PROJ_VERSION }}
          build-args: --self-contained
          dotnet-version: '7.0'
      - name: ls
        run: ls && ls build && echo ${{ steps.build-osx64.outputs.build-path }}
