name: "test for action"
on:
  push:
    branches: [ "test" ]
  
jobs:
  test:
    name: test-action
    runs-on: ubuntu-latest
    
    steps:
      - name: get version
        run: echo "PROJ_VERSION=2.0.0" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: ls before
        run: ls
      - id: build-osx64
      - uses: ./.github/actions/build-dotnet
        with:
          name: 'ConsoleClient'
          runtime: osx-x64
          version: ${{ env.PROJ_VERSION }}
          build-args: --self-contained
          dotnet-version: '7.0'
      - name: ls after
        run: ls 
      - name: ls build
        run: ls build
      - name: check path
        run: echo ${{ steps.build-osx64.outputs.build-path }}
